/*--------------------------------------------------------------------------*\
| This file is used to verify coherence of log generated by IBP in Chipyard. |
| To generate log, please add the Chisel code below at the end of IBP class. |

\*--------------------------------------------------------------------------*/

#include <cstdio>
#include <cstring>

#define COM_STR "[commit]"
#define PRD_STR "[predict]"
#define STR_EQL(str, ref) (strncmp(str, ref, strlen(ref)) == 0)

int main()
{
    while (true)
    {
        char line[1024];
        if (!fgets(line, sizeof(line), stdin))
            break;
        char *p = line;
        if (STR_EQL(p, COM_STR))
        {
            // committing, update structure
        }
        else if (STR_EQL(p, PRD_STR))
        {
            // predicting, check coherence
        }
    }
    return 0;
}
